### ISSUE TITLE
any idea coping with long video input?

### ISSUE THREAD

**Issue by dragen1860** [dvlab-research/MiniGemini#1]
Dear author:
  Thanks for publishing the mini gemini paper.  As Gemini 1.5 support up to one hour long video input for 1fps sampling, I wonder how to adopt your framework to support long video training and inference? thank you.

**Comment by yanwei-li** [comment]
Hi, to support longer videos, it is essential to extend the token processing ability. As you mentioned in Gemini 1.5, it can well handle 1M tokens thus supporting long video, which is far beyond our current LLM ability. We'll consider using other LLMs for this in the future.
