### ISSUE TITLE
可以放一下生成generation_pure_text数据的代码吗

### ISSUE THREAD

**Issue by pennypengpm** [dvlab-research/MiniGemini#109]
可以放一下生成generation_pure_text数据的代码吗，感谢

**Comment by berry-ding** [comment]
+1

**Comment by JulianJuaner** [comment]
The process of generating data involves handling different data sources and formats (such as filtering English data, keeping the format consistent, etc.), and the overall process is quite cumbersome. However, we have already provided the GPT4 prompt we used in Figure 7 of the Appendix of the paper. Here is also some related information for your reference:

SD Prompts (example captions): https://www.gigasheet.com/sample-data/stable-diffusion-prompts
Some example queries: [
    "Show a serene lakeside at dawn.",
    "Depict an astronaut with Earth in the background.",
    "Generate a medieval market.",
    "Generate a neon-lit futuristic city at night.",
    "Portray a lone oak tree in autumn.",
    "Create an image of a dragon on a mountain.",
    "Generate a 1920s jazz club scene.",
    "Visualize a quiet library with old books.",
    "Present a meadow with wildflowers and a rainbow.",
    "Draw a snowy Christmas village with playing children.",
    "Show a Japanese garden in cherry blossom season.",
    "Depict a lighthouse in a stormy sea.”….
    (You can generate more by using GPT4) 
]
Prompt (Appendix Fig. 7)
<img width="555" alt="Screenshot 2024-05-11 at 6 12 07 PM" src="https://github.com/dvlab-research/MGM/assets/37148692/aecba5f6-3faa-47b4-b2a0-531ae02a483e">

**Comment by JulianJuaner** [comment]
Ours generation-related data: https://huggingface.co/datasets/YanweiLi/MGM-Instruction/blob/main/mgm_generation_pure_text.json

**Comment by pennypengpm** [comment]
Thanks
