### ISSUE TITLE
dataset miss problem

### ISSUE THREAD

**Issue by TuuSiwei** [dvlab-research/MiniGemini#116]
I attempted to conduct pre-training for the first stage, during training, I frequently encounter errors such as 'error in loading xxxx' when doing get_item function. What could be the reason for this?

**Comment by tsw123678** [comment]
my data is in the correct directory

**Comment by tsw123678** [comment]
@yanwei-li

**Comment by Murasame-sway** [comment]
sorry, I loss the allava images
