### ISSUE TITLE
error in loading

### ISSUE THREAD

**Issue by TuuSiwei** [dvlab-research/MiniGemini#122]
I successfully completed the pre-training, but during the fine-tuning process, I frequently encounter errors like "error in loading XXX." I have verified that the corresponding XXX images exist in my data folder. What could be the issue causing existing images to still fail to load?

**Comment by tsw123678** [comment]
@yanwei-li

**Comment by Luo-Z13** [comment]
> I successfully completed the pre-training, but during the fine-tuning process, I frequently encounter errors like "error in loading XXX." I have verified that the corresponding XXX images exist in my data folder. What could be the issue causing existing images to still fail to load?

Hello, how do you solve this problem?

**Comment by Murasame-sway** [comment]
> > I successfully completed the pre-training, but during the fine-tuning process, I frequently encounter errors like "error in loading XXX." I have verified that the corresponding XXX images exist in my data folder. What could be the issue causing existing images to still fail to load?
> 
> Hello, how do you solve this problem?

@Luo-Z13，I think there are many possibilities for this error, either your training images are stored in a different directory than the one recorded in json, or you have replaced some models. While the author has blocked the error in the get_item function of the dataset by exception handling, I think you should try to change the get_item function to call the sample function directly to get the error information
