### ISSUE TITLE
loss 0 and grad nan

### ISSUE THREAD

**Issue by TuuSiwei** [dvlab-research/MiniGemini#123]
when I run ./stage_1_2_full_gemma_v2b_336_hr_768.sh finetuning，I encounter 0 loss and nan grad，that’s why？
![image](https://github.com/dvlab-research/MGM/assets/67264710/690af074-08e3-474b-bf13-39e42c88f7f6)

**Comment by Hayoung93** [comment]
Hi @tsw123678 , may I ask you how did this problem has solved?

**Comment by Murasame-sway** [comment]
> Hi @tsw123678 , may I ask you how did this problem has solved?

yes，i find it caused by the high version of deepspeed

**Comment by Hayoung93** [comment]
Thanks a lot!
For someone's information, recommended versions can be found in another [issue](https://github.com/dvlab-research/MGM/issues/42#issuecomment-2049617061)
