### ISSUE TITLE
RuntimeError: shape '[3, 2, 336, 2, 336]' is invalid for input of size 2709504

### ISSUE THREAD

**Issue by lightingvector** [dvlab-research/MiniGemini#17]
command used:
python -m minigemini.serve.cli \
    --model-path work_dirs/Mini-Gemini/Mini-Gemini-13B-HD \
    --image-file image_1.png,image_2.png

**Comment by yanwei-li** [comment]
Thanks for your interest in our work! In current cli file, multi-image inference has not been officially supported. You can try running with a single image.

**Comment by lightingvector** [comment]
okay thank you ! thanks for your great work ^ ^
