### ISSUE TITLE
Where is the data of Generation-related Instructions in Section 3.3?

### ISSUE THREAD

**Issue by jiashenggu** [dvlab-research/MiniGemini#19]
Thank you for your great work!
Could you clarify where the data about Generation-related Instructions in Section 3.3 is located?

**Comment by yanwei-li** [comment]
Hi, please find them here https://huggingface.co/datasets/YanweiLi/Mini-Gemini-Instruction

**Comment by JulianJuaner** [comment]
> Thank you for your great work! Could you clarify where the data about Generation-related Instructions in Section 3.3 is located?

Hi, one simple way to filter out all Generation-related data is to find the trigger tag <GEN> in the first round of conversation in the full instruction dataset.

**Comment by jiezhangGt** [comment]
> > Thank you for your great work! Could you clarify where the data about Generation-related Instructions in Section 3.3 is located?
> 
> @jiashenggu Hi, one simple way to filter out all Generation-related data is to find the trigger tag `<GEN>` in the first round of conversation in the full instruction dataset.

It's not filtered out to contain <GEN> label's data

**Comment by JulianJuaner** [comment]
> > > Thank you for your great work! Could you clarify where the data about Generation-related Instructions in Section 3.3 is located?
> > 
> > 
> > @jiashenggu Hi, one simple way to filter out all Generation-related data is to find the trigger tag `<GEN>` in the first round of conversation in the full instruction dataset.
> 
> It's not filtered out to contain label's data

Sorry for the misunderstanding. You may refer to https://huggingface.co/datasets/YanweiLi/MGM-Instruction/blob/main/mgm_generation_pure_text.json for the generation subset we used. The original instruction data is the full set.

**Comment by jiezhangGt** [comment]
> > > > Thank you for your great work! Could you clarify where the data about Generation-related Instructions in Section 3.3 is located?
> > > 
> > > 
> > > @jiashenggu Hi, one simple way to filter out all Generation-related data is to find the trigger tag `<GEN>` in the first round of conversation in the full instruction dataset.
> > 
> > 
> > It's not filtered out to contain label's data
> 
> Sorry for the misunderstanding. You may refer to https://huggingface.co/datasets/YanweiLi/MGM-Instruction/blob/main/mgm_generation_pure_text.json for the generation subset we used. The original instruction data is the full set.

Get it! thanks for your reply!!
