### ISSUE TITLE
Why does any stage didn't optimize vision encoder?

### ISSUE THREAD

**Issue by lucasjinreal** [dvlab-research/MiniGemini#2]
Nice work, from the scripts provided, seems all `optimize_vision_tower` either `aux` were not used.

Then I have some puzzels:

1. Is that optimize get worse results? 
2. If not finetune the vision tower, how to make it learn new visual tokens?

**Comment by lucasjinreal** [comment]
Have u consider just tuning vision encoder with lora, while full finetuning proj and llm?

**Comment by lucasjinreal** [comment]
Am not really gain from tune any vision encoder, but recently some papers like MM1 etc indicates funetuing ViT could boost performance.

This might related close to how does whole model architecture design.

But from my side, I think we can only make model learn new visual tokens by fineunte vision encoder, this is now I am trying to figure out. For instance, we want model learn how to ocr on multilingual images, this could be hard if vision encoder were frozen, if though it might not related to boost the current benchmark score since they mainly focus on English only.

**Comment by yanwei-li** [comment]
Thanks for your sharing!
