### ISSUE TITLE
Not find vision tower: model_zoo/OpenAI/clip-vit-large-patch14-336

### ISSUE THREAD

**Issue by wangzijian1010** [dvlab-research/MiniGemini#21]
Hi, Nice work! but when i run the example code , i have encounter some problems,when i run `python -m minigemini.serve.cli  --model-path YanweiLi/Mini-Gemini-13B-HD   --image-file Woman.jpg` ,i got the error ValueError: Not find vision tower: model_zoo/OpenAI/clip-vit-large-patch14-336 ,how can i solve this problem thank u!

**Comment by YeTianJHU** [comment]
I think you'll need to download the clip-vit-large-patch14-336 under model_zoo/OpenAI/

**Comment by wangzijian1010** [comment]
> I think you'll need to download the clip-vit-large-patch14-336 under model_zoo/OpenAI/

thank u bro , i appreciate

**Comment by yanwei-li** [comment]
Thanks for the answer @YeTianJHU. Please reopen this issue if not fixed
