### ISSUE TITLE
datasets preparation 

### ISSUE THREAD

**Issue by KevinPanJun** [dvlab-research/MiniGemini#23]
There are some image sources missing in the preparation stage:
  sam/images/: 19982
  wikiart/images/: 500
  share_textvqa/images/: 500
  web-celebrity/images/: 498
  web-landmark/images/: 500
Could you help add these datasets?

**Comment by JulianJuaner** [comment]
Sorry for the inconvenience, those data are from ShareGPT4V-100K, please refer to https://github.com/InternLM/InternLM-XComposer/blob/main/projects/ShareGPT4V/docs/Data.md for image collection. We will further update our README file.

**Comment by yanwei-li** [comment]
Thanks! We fix the data collection in README. Please try it.
