### ISSUE TITLE
Fixing the pretrain and sft stage ALLaVa images issue.

### ISSUE THREAD

**Issue by lucasjinreal** [dvlab-research/MiniGemini#25]
Hi, as previous issue raised, the data all wrong for any data from ALLaVA, they have changed the image names.

What even worse, even tough using url mapping the image names with latest ALLaVa's caption json, still some images were totally can not be found, in latest ALLaVa.

for example:

```
cat ALLaVA-Caption-LAION-4V.json | grep 'https://slideplayer.it/slide/553401/1/images/40/Delayed+relaxation+filling+pattern.jpg' -C 9
```
this url existed in minigemini but **gone at latest ALLava images**

Therefore, please help fix the data first, it emergency. Stops anyone want to reveal the minigemini training and scores.

**Comment by yanwei-li** [comment]
This has been fixed. Please download the data of Mini-Gemini again.

**Comment by lucasjinreal** [comment]
thanks!
