### ISSUE TITLE
No image generated while run python -m minigemini.serve.cli --gen

### ISSUE THREAD

**Issue by Xiaolong-RRL** [dvlab-research/MiniGemini#26]
Dear author:

Thanks for your interesting work.

When I run the following command with the input `What is unusual about this image?`, no image generated in the output:

```
python -m minigemini.serve.cli \
    --model-path work_dirs/Mini-Gemini/Mini-Gemini-2B \
    --image-file examples/extreme_ironing.jpg \
    --gen
```

![image](https://github.com/dvlab-research/MiniGemini/assets/74476562/f5b8f019-53f1-4cce-8768-7209be5089e7)

I wonder if the Mini-Gemini-2B model does not have the ability to generate images? 

And if fine-tuning is needed, which datasets should be used to make the model output `<h> ... </h>`?

Thanks!!

**Comment by yanwei-li** [comment]
Hi, we use the generation data to finetune all the models, including the 2B model. But in some cases, it will not output the generation prompt. So, `Mini-Gemini-13B` and `Mini-Gemini-34B` are highly-recommended if you want to generate images.

**Comment by Xiaolong-RRL** [comment]
It works with Mini-Gemini-34B, Thanks!!!
