### ISSUE TITLE
Mini-Gemini-2B evaluation error

### ISSUE THREAD

**Issue by laserwave** [dvlab-research/MiniGemini#31]
Hi, I follow the instructions to prepare the data and model and get the following error when evaluating the Mini-Gemini-2B.

`AttributeError: 'OpenCLIPVisionTower' object has no attribute 'vision_stem'`

**Comment by laserwave** [comment]
Turn to 7B version and it worked.

**Comment by HongLouyemeng** [comment]
> 换成7B版本就可以了。
老哥Vicuna-7B-v1.5模型出现了 'LlamaForCausalLM' object has no attribute 'get_vision_tower有碰到过吗
