### ISSUE TITLE
batch inference

### ISSUE THREAD

**Issue by mukundkhanna123** [dvlab-research/MiniGemini#32]
Hi could you tell me how I can do batch inferencing? 
I have multiple images and a different prompt for eacg image, so is there a way i can get the output in one go ?

**Comment by yanwei-li** [comment]
Hi, if you want to do batch inference, you need to prepare batched images and input_ids. For example, in `cli.py`, the [input_ids](https://github.com/dvlab-research/MiniGemini/blob/1bf01c16baa6a44217ab837fdee01d64ba92c967/minigemini/serve/cli.py#L195C17-L195C26), [image_tensor](https://github.com/dvlab-research/MiniGemini/blob/1bf01c16baa6a44217ab837fdee01d64ba92c967/minigemini/serve/cli.py#L196), and [image_tensor_aux](https://github.com/dvlab-research/MiniGemini/blob/1bf01c16baa6a44217ab837fdee01d64ba92c967/minigemini/serve/cli.py#L197C52-L197C68) should be prepared with batched inut. And decode the output_id according to the input.

**Comment by mukundkhanna123** [comment]
Hey thank you for answering! 
i tried that but I'm getting the wrong output 
so for reference this is the shape of my input tensors -
input_ids (batch size,1,sequence length)
image_tensor (batch size, 1,5,3,336,336) 
image_tensor_aux (batch_size, 1,3,1536,1536) 
but I'm getting garbage output of shape (1,513) that is totally unrelated to the input 

I tried with removing the extra second dimension but then i run into shape errors
