### ISSUE TITLE
How to get 13K generation-related instructions dataset?

### ISSUE THREAD

**Issue by Xiaolong-RRL** [dvlab-research/MiniGemini#38]
Dear author:

Thanks for your interesting work.

But I am still confused about following questions:
1. How to get 13K generation-related instructions dataset?
2. How to only tuning LLM for generation (or tuning LLM for understanding and generation separately)

Looking forward to your reply~
Thanks!!

**Comment by yanwei-li** [comment]
Hi, thanks for your interest. We release the single 13K data [here](https://huggingface.co/datasets/YanweiLi/Mini-Gemini-Instruction/blob/main/minigemini_generation_pure_text.json). 
In our model, we jointly train the LLM for understanding and generation using the [instruction data](https://huggingface.co/datasets/YanweiLi/Mini-Gemini-Instruction/blob/main/minigemini_instruction.json). If you want to tune the generation data only, you can (1) exclude the 13K data from the combined [instruction data](https://huggingface.co/datasets/YanweiLi/Mini-Gemini-Instruction/blob/main/minigemini_instruction.json), and perform instruction tuning; (2) further fine-tune the model with the provided 13K data as stage-3.

**Comment by JulianJuaner** [comment]
Just to clarify, to avoid overfitting the model to generation, the released subset includes the original data from multi-round conversations (about 6K, LIMA + OpenAssistant2), so the total amount is roughly 19K.
