### ISSUE TITLE
Possible positional embedding in Patch Info Mining process

### ISSUE THREAD

**Issue by penghao-wu** [dvlab-research/MiniGemini#5]
Thanks for sharing your great work. I have a small question about the attention process in the patch info mining module. I found that there is no positional embedding for the high-resolution tokens to indicate their position in the corresponding patch. Do you think adding positional embedding here would be helpful and have you tried this?

**Comment by yanwei-li** [comment]
Hi, thanks for your question. Because all the HR subregions that belong to a same LR query should be equally processed, we do not add positional embedding to it. So, I'm not sure if it could be better with position embedding and it seems cannot bring any potential benefit in my mind.
