### ISSUE TITLE
Training model got some error

### ISSUE THREAD

**Issue by lucasjinreal** [dvlab-research/MiniGemini#6]
```
TypeError: pad_sequence(): argument 'padding_value' (position 3) must be float, not NoneType
```

Am using Qwen as LLM, got above error, what could be the reason? I have checked:

```
if tokenizer.pad_token_id == None:
        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.unk_token
        tokenizer.pad_token_id = tokenizer.encode(tokenizer.pad_token)
```

didnt make it work, any help could be possible?

**Comment by yanwei-li** [comment]
Hi, the pad token here should be adjusted according to different LLMs. Please make sure this token id and unk_token are meaningful.

**Comment by lucasjinreal** [comment]
Solved it. Can u help me take a look on other issue?
