### ISSUE TITLE
Re-opening issue: Mini-Gemini Model Fine-Tuning Anomaly

### ISSUE THREAD

**Issue by lightingvector** [dvlab-research/MiniGemini#61]
I am currently facing an issue with the fine-tuning process of the Mini-Gemini-8x7B. Despite setting up the model for fine-tuning as per the standard configurations and ensuring all steps are correctly followed, the model anomalously saves only 4 safe tensors post-training, whereas it is supposed to save 20, based on its initial setup configurations. 

**Training file:**
```#!/bin/bash
PRETRAIN_NAME=Mini-Gemini-8x7B-Pretrain
FINETUNE_NAME=Mini-Gemini-8x7B-HD
AUX_SIZE=1536
IMAGE_GRID=2
IMAGE_GLOBAL=True
LR_MULTI="model.mm_projector:2,model.vlm_uni:2"


deepspeed --num_gpus 8 minigemini/train/train_mem.py \
    --deepspeed scripts/zero3.json \
    --model_name_or_path Mixtral-8x7B-Instruct-v0.1 \
    --version mistral_instruct \
    --data_path data/instructions.json \
    --image_folder data/images/ \
    --vision_tower model_zoo/OpenAI/clip-vit-large-patch14-336 \
    --vision_tower_aux model_zoo/OpenAI/openclip-convnext-large-d-320-laion2B-s29B-b131K-ft-soup \
    --image_grid $IMAGE_GRID \
    --image_global $IMAGE_GLOBAL \
    --pretrain_mm_mlp_adapter Mini-Gemini-Pretrain/Mini-Gemini-8x7B/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --image_size_aux $AUX_SIZE \
    --bf16 True \
    --output_dir work_dirs/attempt-2-lora \
    --num_train_epochs 1 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "epoch" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 1e-5 \
    --lr_multi $LR_MULTI \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 8192 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
```

**Expected Behavior:**  
The model is expected to handle 20 safe tensors which correspond to various model weights and biases across its architecture. 
 
**Current Anomaly:** 
Post-training, the model inexplicably results in only 4 safe tensors being saved. This is 
evident from the output of the [model.safetensors.index.json](https://github.com/dvlab-research/MiniGemini/files/14997557/model.safetensors.index.json) which should reflect mappings for 20 tensors but only shows 4.

**Comment by yanwei-li** [comment]
Hi, sorry for the late reply. It seems all the 'moe'-related params are not saved, compared with the [official file](https://huggingface.co/YanweiLi/Mini-Gemini-8x7B-HD/blob/main/model.safetensors.index.json). Did you train this model with `transformers==4.36.2` and `deepspeed==0.11.1`? And please also check if [this line](https://github.com/dvlab-research/MiniGemini/blob/367df45c70b582dd7b767d9bad57578b1ca2db7f/minigemini/train/train.py#L1063) is running well.

**Comment by lightingvector** [comment]
File "/home/ubuntu/MiniGemini/minigemini/train/train.py", line 1063, in train
    from deepspeed.utils import set_z3_leaf_modules
ImportError: cannot import name 'set_z3_leaf_modules' from 'deepspeed.utils' (/home/ubuntu/MiniGemini/venv/lib/python3.10/site-packages/deepspeed/utils/__init__.py)

Seems like the problem stems from deepspeed.

**Comment by lightingvector** [comment]
worked ^^ thanks for pointing towards the right direction.
