### ISSUE TITLE
AutoTokenizer resolve error

### ISSUE THREAD

**Issue by yiranyyu** [dvlab-research/MiniGemini#7]
Simply run the demo code as following fails:

```py
python -m minigemini.serve.cli \
    --model-path YanweiLi/Mini-Gemini-2B \
    --image-file ./images/demo_gen.png
```

error message:

```shell
  File "XXXXX/envs/minigemini/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 784, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class GemmaTokenizer does not exist or is not currently imported.
```

Update to newest `transformers` fix this problem

**Comment by yanwei-li** [comment]
Thanks, as declared in README, please upgrade the `transformers` to 4.28 or even 4.29 to support Gemma model.

**Comment by linxid** [comment]
But my transformers is 4.27.2, why have this bug also

**Comment by learningpro** [comment]
pip3 list | grep transformers
transformers              4.36.2

also this big

**Comment by sunyiyou** [comment]
Try pip install -U transformers


> pip3 list | grep transformers transformers 4.36.2
> 
> also this big
